# Generated by Django 5.1.6 on 2025-03-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_sigma', '0002_event_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='processed',
        ),
    ]
